name: Sync Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  sync-sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth

      - name: Run sync script
        env:
          BIZNEST_AGENT: ${{ secrets.BIZNEST_AGENT }}
          CORE: ${{ secrets.CORE }}
          CORE_HANDLER: ${{ secrets.CORE_HANDLER }}
        run: |
          python services/run_sync.py
