name: Sync Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  sync_sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run sheet sync
        run: |
          python main.py
        env:
          BIZNEST_AGENT: ${{ secrets.BIZNEST_AGENT }}
          CORE: ${{ secrets.CORE }}
          CORE_HANDLER: ${{ secrets.CORE_HANDLER }}
