name: BizCORE RUNNER

on:
  workflow_dispatch:  # Run manually, or change to schedule/push as needed

jobs:
  sync-job:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > creds.json

      - name: Run sync service
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=creds.json
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python services/sync_service.py

